// protoc --go_out=pb --go_opt=paths=source_relative --go-grpc_out=pb --go-grpc_opt=paths=source_relative publisher/proto/server.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: proto/server.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Paprika_GetSpreadStream_FullMethodName = "/pb.Paprika/GetSpreadStream"
)

// PaprikaClient is the client API for Paprika service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaprikaClient interface {
	GetSpreadStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MsgSpread], error)
}

type paprikaClient struct {
	cc grpc.ClientConnInterface
}

func NewPaprikaClient(cc grpc.ClientConnInterface) PaprikaClient {
	return &paprikaClient{cc}
}

func (c *paprikaClient) GetSpreadStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MsgSpread], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Paprika_ServiceDesc.Streams[0], Paprika_GetSpreadStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, MsgSpread]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Paprika_GetSpreadStreamClient = grpc.ServerStreamingClient[MsgSpread]

// PaprikaServer is the server API for Paprika service.
// All implementations must embed UnimplementedPaprikaServer
// for forward compatibility.
type PaprikaServer interface {
	GetSpreadStream(*StreamRequest, grpc.ServerStreamingServer[MsgSpread]) error
	mustEmbedUnimplementedPaprikaServer()
}

// UnimplementedPaprikaServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaprikaServer struct{}

func (UnimplementedPaprikaServer) GetSpreadStream(*StreamRequest, grpc.ServerStreamingServer[MsgSpread]) error {
	return status.Errorf(codes.Unimplemented, "method GetSpreadStream not implemented")
}
func (UnimplementedPaprikaServer) mustEmbedUnimplementedPaprikaServer() {}
func (UnimplementedPaprikaServer) testEmbeddedByValue()                 {}

// UnsafePaprikaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaprikaServer will
// result in compilation errors.
type UnsafePaprikaServer interface {
	mustEmbedUnimplementedPaprikaServer()
}

func RegisterPaprikaServer(s grpc.ServiceRegistrar, srv PaprikaServer) {
	// If the following call pancis, it indicates UnimplementedPaprikaServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Paprika_ServiceDesc, srv)
}

func _Paprika_GetSpreadStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PaprikaServer).GetSpreadStream(m, &grpc.GenericServerStream[StreamRequest, MsgSpread]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Paprika_GetSpreadStreamServer = grpc.ServerStreamingServer[MsgSpread]

// Paprika_ServiceDesc is the grpc.ServiceDesc for Paprika service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Paprika_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Paprika",
	HandlerType: (*PaprikaServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSpreadStream",
			Handler:       _Paprika_GetSpreadStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/server.proto",
}
