// protoc --go_out=pb --go_opt=paths=source_relative --go-grpc_out=pb --go-grpc_opt=paths=source_relative publisher/proto/server.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.0
// source: proto/server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"` // cex | cex > futures | cex > futures > symbol. Only 'cex' is supporting now
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_proto_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type MsgTicker struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exchange      string                 `protobuf:"bytes,1,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Market        string                 `protobuf:"bytes,2,opt,name=market,proto3" json:"market,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Ask           float64                `protobuf:"fixed64,4,opt,name=ask,proto3" json:"ask,omitempty"`
	Bid           float64                `protobuf:"fixed64,5,opt,name=bid,proto3" json:"bid,omitempty"`
	Volume        float64                `protobuf:"fixed64,6,opt,name=volume,proto3" json:"volume,omitempty"`
	IsVolumeUsdt  bool                   `protobuf:"varint,7,opt,name=isVolumeUsdt,proto3" json:"isVolumeUsdt,omitempty"`
	Timestamp     int64                  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgTicker) Reset() {
	*x = MsgTicker{}
	mi := &file_proto_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgTicker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgTicker) ProtoMessage() {}

func (x *MsgTicker) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgTicker.ProtoReflect.Descriptor instead.
func (*MsgTicker) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{1}
}

func (x *MsgTicker) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *MsgTicker) GetMarket() string {
	if x != nil {
		return x.Market
	}
	return ""
}

func (x *MsgTicker) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *MsgTicker) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *MsgTicker) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *MsgTicker) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *MsgTicker) GetIsVolumeUsdt() bool {
	if x != nil {
		return x.IsVolumeUsdt
	}
	return false
}

func (x *MsgTicker) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type MsgSpread struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	To            *MsgTicker             `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	From          *MsgTicker             `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Spread        float64                `protobuf:"fixed64,4,opt,name=spread,proto3" json:"spread,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSpread) Reset() {
	*x = MsgSpread{}
	mi := &file_proto_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSpread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSpread) ProtoMessage() {}

func (x *MsgSpread) ProtoReflect() protoreflect.Message {
	mi := &file_proto_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSpread.ProtoReflect.Descriptor instead.
func (*MsgSpread) Descriptor() ([]byte, []int) {
	return file_proto_server_proto_rawDescGZIP(), []int{2}
}

func (x *MsgSpread) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *MsgSpread) GetTo() *MsgTicker {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *MsgSpread) GetFrom() *MsgTicker {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *MsgSpread) GetSpread() float64 {
	if x != nil {
		return x.Spread
	}
	return 0
}

var File_proto_server_proto protoreflect.FileDescriptor

const file_proto_server_proto_rawDesc = "" +
	"\n" +
	"\x12proto/server.proto\x12\x02pb\"%\n" +
	"\rStreamRequest\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\"\xd5\x01\n" +
	"\tMsgTicker\x12\x1a\n" +
	"\bexchange\x18\x01 \x01(\tR\bexchange\x12\x16\n" +
	"\x06market\x18\x02 \x01(\tR\x06market\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x10\n" +
	"\x03ask\x18\x04 \x01(\x01R\x03ask\x12\x10\n" +
	"\x03bid\x18\x05 \x01(\x01R\x03bid\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\x01R\x06volume\x12\"\n" +
	"\fisVolumeUsdt\x18\a \x01(\bR\fisVolumeUsdt\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\"{\n" +
	"\tMsgSpread\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x1d\n" +
	"\x02to\x18\x02 \x01(\v2\r.pb.MsgTickerR\x02to\x12!\n" +
	"\x04from\x18\x03 \x01(\v2\r.pb.MsgTickerR\x04from\x12\x16\n" +
	"\x06spread\x18\x04 \x01(\x01R\x06spread2@\n" +
	"\aPaprika\x125\n" +
	"\x0fGetSpreadStream\x12\x11.pb.StreamRequest\x1a\r.pb.MsgSpread0\x01B*Z(github.com/Xepobopa/Paprika/publisher/pbb\x06proto3"

var (
	file_proto_server_proto_rawDescOnce sync.Once
	file_proto_server_proto_rawDescData []byte
)

func file_proto_server_proto_rawDescGZIP() []byte {
	file_proto_server_proto_rawDescOnce.Do(func() {
		file_proto_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_server_proto_rawDesc), len(file_proto_server_proto_rawDesc)))
	})
	return file_proto_server_proto_rawDescData
}

var file_proto_server_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_server_proto_goTypes = []any{
	(*StreamRequest)(nil), // 0: pb.StreamRequest
	(*MsgTicker)(nil),     // 1: pb.MsgTicker
	(*MsgSpread)(nil),     // 2: pb.MsgSpread
}
var file_proto_server_proto_depIdxs = []int32{
	1, // 0: pb.MsgSpread.to:type_name -> pb.MsgTicker
	1, // 1: pb.MsgSpread.from:type_name -> pb.MsgTicker
	0, // 2: pb.Paprika.GetSpreadStream:input_type -> pb.StreamRequest
	2, // 3: pb.Paprika.GetSpreadStream:output_type -> pb.MsgSpread
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_server_proto_init() }
func file_proto_server_proto_init() {
	if File_proto_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_server_proto_rawDesc), len(file_proto_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_server_proto_goTypes,
		DependencyIndexes: file_proto_server_proto_depIdxs,
		MessageInfos:      file_proto_server_proto_msgTypes,
	}.Build()
	File_proto_server_proto = out.File
	file_proto_server_proto_goTypes = nil
	file_proto_server_proto_depIdxs = nil
}
